Site/MyAvailability/MyAvailability/Models/Availability.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MyAvailability.Models
{
    public class Availability
    {
        [Key, Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int EmployeeID { get; set; }

        [Key, Column(Order = 1)]
        public int Day { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:HH:mm}")]
        public DateTime? StartTime { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:HH:mm}")]
        public DateTime? EndTime { get; set; }

        public virtual Employee Employee { get; set; }
    }

    public class AvailabilityDbContext : DbContext
    {
        public DbSet<Availability> Availabilities { get; set; }
    }
}

Site/MyAvailability/MyAvailability/Controllers/AvailabilitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyAvailability.Models;

namespace MyAvailability.Controllers
{
    public class AvailabilitiesController : Controller
    {
        private EmployeeContext employeeContext = new EmployeeContext();

        // GET: Availabilities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Availability> availability =
                employeeContext.Availabilities
                .Where(a => a.EmployeeID == id)
                .ToList();
            if (availability.Count <= 0)
            {
                return HttpNotFound();
            }
            return View(availability);
        }

        // GET: Availabilities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Availability> availabilities = new List<Availability>();
            for (int i = 0; i < 7; i++)
            {
                availabilities.Add(employeeContext.Availabilities.Find(id, i));
            }
            if (availabilities.Count <= 0)
            {
                return HttpNotFound();
            }
            return View(availabilities);
        }

        // POST: Availabilities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IEnumerable<Availability> availabilities)
        {
            if (ModelState.IsValid)
            {
                foreach (Availability availability in availabilities)
                {
                    employeeContext.Entry(availability).State = EntityState.Modified;
                }
                employeeContext.SaveChanges();
                return RedirectToAction("Details", new { id = availabilities.FirstOrDefault().EmployeeID });
            }
            return View(availabilities);
        }
    }
}

Site/MyAvailability/MyAvailability/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyAvailability.Models;

namespace MyAvailability.Controllers
{
    public class EmployeesController : Controller
    {
        private EmployeeContext employeeContext = new EmployeeContext();

        // GET: Employees
        public ActionResult Index()
        {
            return View(employeeContext.Employees.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = employeeContext.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        public ActionResult Availability(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Availability> availability =
                employeeContext.Availabilities
                .Where(a => a.EmployeeID == id)
                .ToList();
            if (availability.Count <= 0)
            {
                return HttpNotFound();
            }
            return View(availability);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeID,FirstName,LastName,DateOfBirth,IsAdmin")] Employee employee)
        {
            if (ModelState.IsValid && employee.EmployeeID != 0)
            {
                // Add the employee
                employeeContext.Employees.Add(employee);
                employeeContext.SaveChanges();

                // Add an availability for the employee

                for (int i = 0; i < 7; i++)
                {
                    employeeContext.Availabilities.Add(
                        new Availability()
                        {
                            EmployeeID = employee.EmployeeID,
                            Day = i,
                            StartTime = DateTime.Now,
                            EndTime = DateTime.Now
                        }
                    );
                }
                employeeContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = employeeContext.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeID,FirstName,LastName,DateOfBirth,IsAdmin")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employeeContext.Entry(employee).State = EntityState.Modified;
                employeeContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = employeeContext.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = employeeContext.Employees.Find(id);
            employeeContext.Employees.Remove(employee);
            employeeContext.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                employeeContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Site/MyAvailability/MyAvailability/Views/Availabilities/Create.cshtml
@model MyAvailability.Models.Availability

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Availability</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Site/MyAvailability/MyAvailability/Views/Availabilities/Delete.cshtml
@model MyAvailability.Models.Availability

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Availability</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Site/MyAvailability/MyAvailability/Views/Availabilities/Details.cshtml
@model IEnumerable<MyAvailability.Models.Availability>

@{
    ViewBag.Title = "Availability";
}

<h2>Availability</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FirstOrDefault().EmployeeID }) |
    @Html.ActionLink("Back", "Details",
                "Employees", new { id = Model.FirstOrDefault().EmployeeID }, null)
</p>

Site/MyAvailability/MyAvailability/Views/Availabilities/Edit.cshtml
@model List<MyAvailability.Models.Availability>

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <h4>Availability</h4>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => Model[0].StartTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => Model[0].EndTime)
                </th>
            </tr>

            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    @Html.HiddenFor(m => Model[i].EmployeeID)
                    @Html.HiddenFor(m => Model[i].Day)
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.EditorFor(model => Model[i].StartTime, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => Model[i].StartTime, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.EditorFor(model => Model[i].EndTime, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => Model[i].EndTime, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </table>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => Model.FirstOrDefault().EmployeeID)

        @Html.HiddenFor(model => Model.FirstOrDefault().Day)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Details", new { id = Model.FirstOrDefault().EmployeeID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Site/MyAvailability/MyAvailability/Views/Availabilities/Index.cshtml
@model IEnumerable<MyAvailability.Models.Availability>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>